// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeckType string

const (
	DeckTypeGrammar    DeckType = "grammar"
	DeckTypeVocabulary DeckType = "vocabulary"
)

func (e *DeckType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeckType(s)
	case string:
		*e = DeckType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeckType: %T", src)
	}
	return nil
}

type NullDeckType struct {
	DeckType DeckType
	Valid    bool // Valid is true if DeckType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeckType) Scan(value interface{}) error {
	if value == nil {
		ns.DeckType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeckType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeckType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeckType), nil
}

type Card struct {
	ID              int64
	DeckID          int64
	KoreanWord      string
	EnglishWord     string
	Context         pgtype.Text
	ExampleSentence pgtype.Text
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type Deck struct {
	ID        int64
	Name      string
	Type      DeckType
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Setting struct {
	ID          int64
	UserID      int64
	CardsPerDay int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID            int64
	Name          string
	Email         string
	PasswordHash  string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
	IsActive      bool
	EmailVerified bool
}

type UserCard struct {
	ID             int64
	UserID         int64
	CardID         int64
	Efactor        float64
	Interval       int32
	Repetitions    int32
	LastReviewedAt pgtype.Timestamptz
	NextReviewAt   pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}
