// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (
  deck_id, korean_word, english_word, context, example_sentence
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, deck_id, korean_word, english_word, context, example_sentence, created_at, updated_at, deleted_at
`

type CreateCardParams struct {
	DeckID          int64
	KoreanWord      string
	EnglishWord     string
	Context         pgtype.Text
	ExampleSentence pgtype.Text
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.DeckID,
		arg.KoreanWord,
		arg.EnglishWord,
		arg.Context,
		arg.ExampleSentence,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.KoreanWord,
		&i.EnglishWord,
		&i.Context,
		&i.ExampleSentence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (
  name, type
) VALUES (
  $1, $2
)
RETURNING id, name, type, created_at, updated_at, deleted_at
`

type CreateDeckParams struct {
	Name string
	Type DeckType
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRow(ctx, createDeck, arg.Name, arg.Type)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, email, password_hash
) VALUES (
  $1, $2, $3
)
RETURNING id, name, email, password_hash, created_at, updated_at, deleted_at, is_active, email_verified
`

type CreateUserParams struct {
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsActive,
		&i.EmailVerified,
	)
	return i, err
}

const createUserCard = `-- name: CreateUserCard :one
INSERT INTO user_cards (
  user_id, card_id
) VALUES (
  $1, $2
)
RETURNING id, user_id, card_id, efactor, interval, repetitions, last_reviewed_at, next_review_at, created_at, updated_at, deleted_at
`

type CreateUserCardParams struct {
	UserID int64
	CardID int64
}

func (q *Queries) CreateUserCard(ctx context.Context, arg CreateUserCardParams) (UserCard, error) {
	row := q.db.QueryRow(ctx, createUserCard, arg.UserID, arg.CardID)
	var i UserCard
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.Efactor,
		&i.Interval,
		&i.Repetitions,
		&i.LastReviewedAt,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
UPDATE cards
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCard, id)
	return err
}

const deleteDeck = `-- name: DeleteDeck :exec
UPDATE decks
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDeck, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users
SET deleted_at = NOW()
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const deleteUserCard = `-- name: DeleteUserCard :exec
DELETE FROM user_cards
WHERE user_id = $1 AND card_id = $2
`

type DeleteUserCardParams struct {
	UserID int64
	CardID int64
}

func (q *Queries) DeleteUserCard(ctx context.Context, arg DeleteUserCardParams) error {
	_, err := q.db.Exec(ctx, deleteUserCard, arg.UserID, arg.CardID)
	return err
}

const getCard = `-- name: GetCard :one
SELECT id, deck_id, korean_word, english_word, context, example_sentence, created_at, updated_at, deleted_at FROM cards
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCard(ctx context.Context, id int64) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.KoreanWord,
		&i.EnglishWord,
		&i.Context,
		&i.ExampleSentence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeck = `-- name: GetDeck :one
SELECT id, name, type, created_at, updated_at, deleted_at FROM decks
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetDeck(ctx context.Context, id int64) (Deck, error) {
	row := q.db.QueryRow(ctx, getDeck, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at, is_active, email_verified FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.IsActive,
		&i.EmailVerified,
	)
	return i, err
}

const getUserCards = `-- name: GetUserCards :many
SELECT id, user_id, card_id, efactor, interval, repetitions, last_reviewed_at, next_review_at, created_at, updated_at, deleted_at FROM user_cards
WHERE user_id = $1
ORDER BY next_review_at ASC
`

func (q *Queries) GetUserCards(ctx context.Context, userID int64) ([]UserCard, error) {
	rows, err := q.db.Query(ctx, getUserCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCard
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Efactor,
			&i.Interval,
			&i.Repetitions,
			&i.LastReviewedAt,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCardsDueForReview = `-- name: GetUserCardsDueForReview :many
SELECT id, user_id, card_id, efactor, interval, repetitions, last_reviewed_at, next_review_at, created_at, updated_at, deleted_at FROM user_cards
WHERE user_id = $1 AND next_review_at <= NOW()
ORDER BY next_review_at ASC
`

func (q *Queries) GetUserCardsDueForReview(ctx context.Context, userID int64) ([]UserCard, error) {
	rows, err := q.db.Query(ctx, getUserCardsDueForReview, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCard
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Efactor,
			&i.Interval,
			&i.Repetitions,
			&i.LastReviewedAt,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCardsDueForReviewAfter = `-- name: GetUserCardsDueForReviewAfter :many
SELECT id, user_id, card_id, efactor, interval, repetitions, last_reviewed_at, next_review_at, created_at, updated_at, deleted_at FROM user_cards
WHERE user_id = $1 AND next_review_at <= NOW() AND next_review_at > $2
ORDER BY next_review_at ASC
`

type GetUserCardsDueForReviewAfterParams struct {
	UserID       int64
	NextReviewAt pgtype.Timestamptz
}

func (q *Queries) GetUserCardsDueForReviewAfter(ctx context.Context, arg GetUserCardsDueForReviewAfterParams) ([]UserCard, error) {
	rows, err := q.db.Query(ctx, getUserCardsDueForReviewAfter, arg.UserID, arg.NextReviewAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCard
	for rows.Next() {
		var i UserCard
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Efactor,
			&i.Interval,
			&i.Repetitions,
			&i.LastReviewedAt,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCardsDueForReviewCount = `-- name: GetUserCardsDueForReviewCount :one
SELECT COUNT(*) FROM user_cards
WHERE user_id = $1 AND next_review_at <= NOW()
`

func (q *Queries) GetUserCardsDueForReviewCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCardsDueForReviewCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listDecks = `-- name: ListDecks :many
SELECT id, name, type, created_at, updated_at, deleted_at FROM decks
ORDER BY name
`

func (q *Queries) ListDecks(ctx context.Context) ([]Deck, error) {
	rows, err := q.db.Query(ctx, listDecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password_hash, created_at, updated_at, deleted_at, is_active, email_verified FROM users
ORDER BY name
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.IsActive,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCard = `-- name: UpdateCard :exec
UPDATE cards
SET deck_id = $2,
    korean_word = $3,
    english_word = $4,
    context = $5,
    example_sentence = $6,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCardParams struct {
	ID              int64
	DeckID          int64
	KoreanWord      string
	EnglishWord     string
	Context         pgtype.Text
	ExampleSentence pgtype.Text
}

func (q *Queries) UpdateCard(ctx context.Context, arg UpdateCardParams) error {
	_, err := q.db.Exec(ctx, updateCard,
		arg.ID,
		arg.DeckID,
		arg.KoreanWord,
		arg.EnglishWord,
		arg.Context,
		arg.ExampleSentence,
	)
	return err
}

const updateDeck = `-- name: UpdateDeck :exec
UPDATE decks
SET name = $2,
    type = $3,
    updated_at = NOW()
WHERE id = $1
`

type UpdateDeckParams struct {
	ID   int64
	Name string
	Type DeckType
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) error {
	_, err := q.db.Exec(ctx, updateDeck, arg.ID, arg.Name, arg.Type)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
  set name = $2,
  email = $3,
  password_hash = $4,
  updated_at = NOW()
WHERE id = $1
`

type UpdateUserParams struct {
	ID           int64
	Name         string
	Email        string
	PasswordHash string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
	)
	return err
}

const updateUserCard = `-- name: UpdateUserCard :exec
UPDATE user_cards
SET efactor = $3,
    interval = $4,
    repetitions = $5,
    last_reviewed_at = $6,
    next_review_at = $7,
    updated_at = NOW()
WHERE user_id = $1 AND card_id = $2
`

type UpdateUserCardParams struct {
	UserID         int64
	CardID         int64
	Efactor        float64
	Interval       int32
	Repetitions    int32
	LastReviewedAt pgtype.Timestamptz
	NextReviewAt   pgtype.Timestamptz
}

func (q *Queries) UpdateUserCard(ctx context.Context, arg UpdateUserCardParams) error {
	_, err := q.db.Exec(ctx, updateUserCard,
		arg.UserID,
		arg.CardID,
		arg.Efactor,
		arg.Interval,
		arg.Repetitions,
		arg.LastReviewedAt,
		arg.NextReviewAt,
	)
	return err
}

const updateUserSettings = `-- name: UpdateUserSettings :exec
UPDATE settings
SET cards_per_day = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserSettingsParams struct {
	UserID      int64
	CardsPerDay int32
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) error {
	_, err := q.db.Exec(ctx, updateUserSettings, arg.UserID, arg.CardsPerDay)
	return err
}
