// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: auth.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"email" binding:"required,email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" binding:"required,email"`
	// @gotags: json:"password" binding:"required"
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequestBody) Reset() {
	*x = LoginRequestBody{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequestBody) ProtoMessage() {}

func (x *LoginRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequestBody.ProtoReflect.Descriptor instead.
func (*LoginRequestBody) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequestBody) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequestBody) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterRequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"email" binding:"required,email"
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email" binding:"required,email"`
	// @gotags: json:"password" binding:"required"
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password" binding:"required"`
	// @gotags: json:"name" binding:"required"
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name" binding:"required"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequestBody) Reset() {
	*x = RegisterRequestBody{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequestBody) ProtoMessage() {}

func (x *RegisterRequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequestBody.ProtoReflect.Descriptor instead.
func (*RegisterRequestBody) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequestBody) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequestBody) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequestBody) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResendVerificationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"email"
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResendVerificationRequest) Reset() {
	*x = ResendVerificationRequest{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResendVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResendVerificationRequest) ProtoMessage() {}

func (x *ResendVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResendVerificationRequest.ProtoReflect.Descriptor instead.
func (*ResendVerificationRequest) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ResendVerificationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x05types\"D\n" +
	"\x10LoginRequestBody\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"[\n" +
	"\x13RegisterRequestBody\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"1\n" +
	"\x19ResendVerificationRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05emailB.Z,github.com/Fankhauserli/voabkr-backend/typesb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_auth_proto_goTypes = []any{
	(*LoginRequestBody)(nil),          // 0: types.LoginRequestBody
	(*RegisterRequestBody)(nil),       // 1: types.RegisterRequestBody
	(*ResendVerificationRequest)(nil), // 2: types.ResendVerificationRequest
}
var file_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
