// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: card.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @gotags: json:"deckId"
	DeckId uint32 `protobuf:"varint,2,opt,name=deck_id,json=deckId,proto3" json:"deckId"`
	// @gotags: json:"koreanWord"
	KoreanWord string `protobuf:"bytes,3,opt,name=korean_word,json=koreanWord,proto3" json:"koreanWord"`
	// @gotags: json:"englishWord"
	EnglishWord string `protobuf:"bytes,4,opt,name=english_word,json=englishWord,proto3" json:"englishWord"`
	// @gotags: json:"context"
	Context string `protobuf:"bytes,5,opt,name=context,proto3" json:"context"`
	// @gotags: json:"example"
	Example       string `protobuf:"bytes,6,opt,name=example,proto3" json:"example"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_card_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Card) GetDeckId() uint32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *Card) GetKoreanWord() string {
	if x != nil {
		return x.KoreanWord
	}
	return ""
}

func (x *Card) GetEnglishWord() string {
	if x != nil {
		return x.EnglishWord
	}
	return ""
}

func (x *Card) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *Card) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type CardRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"deckId"
	DeckId uint32 `protobuf:"varint,1,opt,name=deck_id,json=deckId,proto3" json:"deckId"`
	// @gotags: json:"koreanWord"
	KoreanWord string `protobuf:"bytes,2,opt,name=korean_word,json=koreanWord,proto3" json:"koreanWord"`
	// @gotags: json:"englishWord"
	EnglishWord string `protobuf:"bytes,3,opt,name=english_word,json=englishWord,proto3" json:"englishWord"`
	// @gotags: json:"context"
	Context string `protobuf:"bytes,4,opt,name=context,proto3" json:"context"`
	// @gotags: json:"example"
	Example       string `protobuf:"bytes,5,opt,name=example,proto3" json:"example"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardRequest) Reset() {
	*x = CardRequest{}
	mi := &file_card_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardRequest) ProtoMessage() {}

func (x *CardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardRequest.ProtoReflect.Descriptor instead.
func (*CardRequest) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{1}
}

func (x *CardRequest) GetDeckId() uint32 {
	if x != nil {
		return x.DeckId
	}
	return 0
}

func (x *CardRequest) GetKoreanWord() string {
	if x != nil {
		return x.KoreanWord
	}
	return ""
}

func (x *CardRequest) GetEnglishWord() string {
	if x != nil {
		return x.EnglishWord
	}
	return ""
}

func (x *CardRequest) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *CardRequest) GetExample() string {
	if x != nil {
		return x.Example
	}
	return ""
}

type CardList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"cards"
	Cards         []*Card `protobuf:"bytes,1,rep,name=cards,proto3" json:"cards"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardList) Reset() {
	*x = CardList{}
	mi := &file_card_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardList) ProtoMessage() {}

func (x *CardList) ProtoReflect() protoreflect.Message {
	mi := &file_card_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardList.ProtoReflect.Descriptor instead.
func (*CardList) Descriptor() ([]byte, []int) {
	return file_card_proto_rawDescGZIP(), []int{2}
}

func (x *CardList) GetCards() []*Card {
	if x != nil {
		return x.Cards
	}
	return nil
}

var File_card_proto protoreflect.FileDescriptor

const file_card_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"card.proto\x12\x05types\"\xa7\x01\n" +
	"\x04Card\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\adeck_id\x18\x02 \x01(\rR\x06deckId\x12\x1f\n" +
	"\vkorean_word\x18\x03 \x01(\tR\n" +
	"koreanWord\x12!\n" +
	"\fenglish_word\x18\x04 \x01(\tR\venglishWord\x12\x18\n" +
	"\acontext\x18\x05 \x01(\tR\acontext\x12\x18\n" +
	"\aexample\x18\x06 \x01(\tR\aexample\"\x9e\x01\n" +
	"\vCardRequest\x12\x17\n" +
	"\adeck_id\x18\x01 \x01(\rR\x06deckId\x12\x1f\n" +
	"\vkorean_word\x18\x02 \x01(\tR\n" +
	"koreanWord\x12!\n" +
	"\fenglish_word\x18\x03 \x01(\tR\venglishWord\x12\x18\n" +
	"\acontext\x18\x04 \x01(\tR\acontext\x12\x18\n" +
	"\aexample\x18\x05 \x01(\tR\aexample\"-\n" +
	"\bCardList\x12!\n" +
	"\x05cards\x18\x01 \x03(\v2\v.types.CardR\x05cardsB.Z,github.com/Fankhauserli/voabkr-backend/typesb\x06proto3"

var (
	file_card_proto_rawDescOnce sync.Once
	file_card_proto_rawDescData []byte
)

func file_card_proto_rawDescGZIP() []byte {
	file_card_proto_rawDescOnce.Do(func() {
		file_card_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)))
	})
	return file_card_proto_rawDescData
}

var file_card_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_card_proto_goTypes = []any{
	(*Card)(nil),        // 0: types.Card
	(*CardRequest)(nil), // 1: types.CardRequest
	(*CardList)(nil),    // 2: types.CardList
}
var file_card_proto_depIdxs = []int32{
	0, // 0: types.CardList.cards:type_name -> types.Card
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_card_proto_init() }
func file_card_proto_init() {
	if File_card_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_proto_rawDesc), len(file_card_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_card_proto_goTypes,
		DependencyIndexes: file_card_proto_depIdxs,
		MessageInfos:      file_card_proto_msgTypes,
	}.Build()
	File_card_proto = out.File
	file_card_proto_goTypes = nil
	file_card_proto_depIdxs = nil
}
