// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: deck.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Deck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"id"
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	// @gotags: json:"type"
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Deck) Reset() {
	*x = Deck{}
	mi := &file_deck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Deck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deck) ProtoMessage() {}

func (x *Deck) ProtoReflect() protoreflect.Message {
	mi := &file_deck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deck.ProtoReflect.Descriptor instead.
func (*Deck) Descriptor() ([]byte, []int) {
	return file_deck_proto_rawDescGZIP(), []int{0}
}

func (x *Deck) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Deck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Deck) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	// @gotags: json:"type"
	Type          string `protobuf:"bytes,2,opt,name=type,proto3" json:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckRequest) Reset() {
	*x = DeckRequest{}
	mi := &file_deck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckRequest) ProtoMessage() {}

func (x *DeckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_deck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckRequest.ProtoReflect.Descriptor instead.
func (*DeckRequest) Descriptor() ([]byte, []int) {
	return file_deck_proto_rawDescGZIP(), []int{1}
}

func (x *DeckRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeckRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DeckList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"decks"
	Decks         []*Deck `protobuf:"bytes,1,rep,name=decks,proto3" json:"decks"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeckList) Reset() {
	*x = DeckList{}
	mi := &file_deck_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeckList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeckList) ProtoMessage() {}

func (x *DeckList) ProtoReflect() protoreflect.Message {
	mi := &file_deck_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeckList.ProtoReflect.Descriptor instead.
func (*DeckList) Descriptor() ([]byte, []int) {
	return file_deck_proto_rawDescGZIP(), []int{2}
}

func (x *DeckList) GetDecks() []*Deck {
	if x != nil {
		return x.Decks
	}
	return nil
}

var File_deck_proto protoreflect.FileDescriptor

const file_deck_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"deck.proto\x12\x05types\">\n" +
	"\x04Deck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"5\n" +
	"\vDeckRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"-\n" +
	"\bDeckList\x12!\n" +
	"\x05decks\x18\x01 \x03(\v2\v.types.DeckR\x05decksB.Z,github.com/Fankhauserli/voabkr-backend/typesb\x06proto3"

var (
	file_deck_proto_rawDescOnce sync.Once
	file_deck_proto_rawDescData []byte
)

func file_deck_proto_rawDescGZIP() []byte {
	file_deck_proto_rawDescOnce.Do(func() {
		file_deck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_deck_proto_rawDesc), len(file_deck_proto_rawDesc)))
	})
	return file_deck_proto_rawDescData
}

var file_deck_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_deck_proto_goTypes = []any{
	(*Deck)(nil),        // 0: types.Deck
	(*DeckRequest)(nil), // 1: types.DeckRequest
	(*DeckList)(nil),    // 2: types.DeckList
}
var file_deck_proto_depIdxs = []int32{
	0, // 0: types.DeckList.decks:type_name -> types.Deck
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_deck_proto_init() }
func file_deck_proto_init() {
	if File_deck_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_deck_proto_rawDesc), len(file_deck_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_deck_proto_goTypes,
		DependencyIndexes: file_deck_proto_depIdxs,
		MessageInfos:      file_deck_proto_msgTypes,
	}.Build()
	File_deck_proto = out.File
	file_deck_proto_goTypes = nil
	file_deck_proto_depIdxs = nil
}
