// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: settings.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"cardsPerDay"
	CardsPerDay uint32 `protobuf:"varint,1,opt,name=cards_per_day,json=cardsPerDay,proto3" json:"cardsPerDay"`
	// @gotags: json:"studyDirection"
	StudyDirection string `protobuf:"bytes,2,opt,name=study_direction,json=studyDirection,proto3" json:"studyDirection"`
	// @gotags: json:"scratchPadEnabled"
	ScratchPadEnabled bool `protobuf:"varint,3,opt,name=scratch_pad_enabled,json=scratchPadEnabled,proto3" json:"scratchPadEnabled"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{0}
}

func (x *SettingsResponse) GetCardsPerDay() uint32 {
	if x != nil {
		return x.CardsPerDay
	}
	return 0
}

func (x *SettingsResponse) GetStudyDirection() string {
	if x != nil {
		return x.StudyDirection
	}
	return ""
}

func (x *SettingsResponse) GetScratchPadEnabled() bool {
	if x != nil {
		return x.ScratchPadEnabled
	}
	return false
}

type UpdateSettingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: json:"cardsPerDay"
	CardsPerDay *uint32 `protobuf:"varint,1,opt,name=cards_per_day,json=cardsPerDay,proto3,oneof" json:"cardsPerDay"`
	// @gotags: json:"studyDirection"
	StudyDirection *string `protobuf:"bytes,2,opt,name=study_direction,json=studyDirection,proto3,oneof" json:"studyDirection"`
	// @gotags: json:"scratchPadEnabled"
	ScratchPadEnabled *bool `protobuf:"varint,3,opt,name=scratch_pad_enabled,json=scratchPadEnabled,proto3,oneof" json:"scratchPadEnabled"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_settings_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateSettingsRequest) GetCardsPerDay() uint32 {
	if x != nil && x.CardsPerDay != nil {
		return *x.CardsPerDay
	}
	return 0
}

func (x *UpdateSettingsRequest) GetStudyDirection() string {
	if x != nil && x.StudyDirection != nil {
		return *x.StudyDirection
	}
	return ""
}

func (x *UpdateSettingsRequest) GetScratchPadEnabled() bool {
	if x != nil && x.ScratchPadEnabled != nil {
		return *x.ScratchPadEnabled
	}
	return false
}

var File_settings_proto protoreflect.FileDescriptor

const file_settings_proto_rawDesc = "" +
	"\n" +
	"\x0esettings.proto\x12\x05types\"\x8f\x01\n" +
	"\x10SettingsResponse\x12\"\n" +
	"\rcards_per_day\x18\x01 \x01(\rR\vcardsPerDay\x12'\n" +
	"\x0fstudy_direction\x18\x02 \x01(\tR\x0estudyDirection\x12.\n" +
	"\x13scratch_pad_enabled\x18\x03 \x01(\bR\x11scratchPadEnabled\"\xe1\x01\n" +
	"\x15UpdateSettingsRequest\x12'\n" +
	"\rcards_per_day\x18\x01 \x01(\rH\x00R\vcardsPerDay\x88\x01\x01\x12,\n" +
	"\x0fstudy_direction\x18\x02 \x01(\tH\x01R\x0estudyDirection\x88\x01\x01\x123\n" +
	"\x13scratch_pad_enabled\x18\x03 \x01(\bH\x02R\x11scratchPadEnabled\x88\x01\x01B\x10\n" +
	"\x0e_cards_per_dayB\x12\n" +
	"\x10_study_directionB\x16\n" +
	"\x14_scratch_pad_enabledB.Z,github.com/Fankhauserli/voabkr-backend/typesb\x06proto3"

var (
	file_settings_proto_rawDescOnce sync.Once
	file_settings_proto_rawDescData []byte
)

func file_settings_proto_rawDescGZIP() []byte {
	file_settings_proto_rawDescOnce.Do(func() {
		file_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)))
	})
	return file_settings_proto_rawDescData
}

var file_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_proto_goTypes = []any{
	(*SettingsResponse)(nil),      // 0: types.SettingsResponse
	(*UpdateSettingsRequest)(nil), // 1: types.UpdateSettingsRequest
}
var file_settings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settings_proto_init() }
func file_settings_proto_init() {
	if File_settings_proto != nil {
		return
	}
	file_settings_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_proto_rawDesc), len(file_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_proto_goTypes,
		DependencyIndexes: file_settings_proto_depIdxs,
		MessageInfos:      file_settings_proto_msgTypes,
	}.Build()
	File_settings_proto = out.File
	file_settings_proto_goTypes = nil
	file_settings_proto_depIdxs = nil
}
