#!/usr/bin/env bash
set -euo pipefail

# Ensure GOPATH/bin and GOBIN are in PATH if go is available
if command -v go >/dev/null 2>&1; then
  GOBIN_DIR="$(go env GOBIN)"
  GOPATH_DIR="$(go env GOPATH)"
  [ -n "$GOBIN_DIR" ] && [ -d "$GOBIN_DIR" ] && export PATH="$GOBIN_DIR:$PATH"
  [ -n "$GOPATH_DIR" ] && [ -d "$GOPATH_DIR/bin" ] && export PATH="$GOPATH_DIR/bin:$PATH"
fi

if ! command -v protoc >/dev/null 2>&1; then
  echo "Error: protoc (Protocol Buffers compiler) is required but not installed." >&2
  echo "Please install protobuf compiler (e.g., 'sudo apt-get install protobuf-compiler' or 'brew install protobuf')." >&2
  exit 1
fi

# Auto-install Go protobuf plugins if missing
if ! command -v protoc-gen-go >/dev/null 2>&1; then
  echo "protoc-gen-go not found, installing..." >&2
  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
fi
if ! command -v protoc-gen-go-json >/dev/null 2>&1; then
  echo "protoc-gen-go-json not found, installing..." >&2
  go install github.com/mitchellh/protoc-gen-go-json@latest
fi
if ! command -v protoc-go-inject-tag >/dev/null 2>&1; then
  echo "protoc-go-inject-tag not found, installing..." >&2
  go install github.com/favadi/protoc-go-inject-tag@latest
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

# 1. Generate Go protobuf structs
protoc -I=proto \
  --go_out=. --go_opt=module=github.com/Fankhauserli/voabkr-backend \
  proto/*.proto

# 2. Generate JSON marshalers/unmarshalers using protoc-gen-go-json
# Note: settings.proto contains proto3 optional fields which protoc-gen-go-json does not declare support for,
# so we run protoc-gen-go-json on the other proto files and generate settings.pb.json.go directly.
protoc -I=proto \
  --go-json_out=emit_defaults=true,allow_unknown=true:. --go-json_opt=module=github.com/Fankhauserli/voabkr-backend \
  proto/auth.proto proto/card.proto proto/deck.proto proto/review.proto proto/user.proto

cat << 'EOF' > types/settings.pb.json.go
// Code generated by protoc-gen-go-json. DO NOT EDIT.
// source: settings.proto

package types

import (
	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSON implements json.Marshaler
func (msg *SettingsResponse) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
		UseProtoNames:   false,
	}.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *SettingsResponse) UnmarshalJSON(b []byte) error {
	return protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}.Unmarshal(b, msg)
}

// MarshalJSON implements json.Marshaler
func (msg *UpdateSettingsRequest) MarshalJSON() ([]byte, error) {
	return protojson.MarshalOptions{
		UseEnumNumbers:  false,
		EmitUnpopulated: true,
		UseProtoNames:   false,
	}.Marshal(msg)
}

// UnmarshalJSON implements json.Unmarshaler
func (msg *UpdateSettingsRequest) UnmarshalJSON(b []byte) error {
	return protojson.UnmarshalOptions{
		DiscardUnknown: true,
	}.Unmarshal(b, msg)
}
EOF

# 3. Inject custom struct tags (e.g. @gotags: json:"...")
for f in types/*.pb.go; do
  protoc-go-inject-tag -input="$f"
done
